version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: tcdd_mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  bot:
    build: .
    container_name: tcdd_bot_local
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app:/app/app  # Kodu her kaydettiğinde Docker'ın içine anında yansıması için volume bağladık!

volumes:
  mysql_data: